[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.7"
legion = "0.4.0"
ron = "0.8.1"
serde = "1.0.198"

[profile.release]
lto = "thin"
